[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://bank-app-3-1fn0.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
